### PR TITLE
Added Exercise Folder

### PR DESCRIPTION
**Pull request by georgerahul24**
I will write more exercises later

### CODE REVIEW

**Comment by georgerahul24** [comment]
Should i make a questions.md file and link these?
Or is this enough?

**Comment by georgerahul24** [comment]
I have added README.md for excercie folder(Refer the last commit only please)

**Comment by Akuli** [comment]
Can you move everything into existing files (such as `basics/loops.md`) instead of making new files and directories?

**Comment by georgerahul24** [comment]
Sure thing

**Comment by georgerahul24** [comment]
I will close this request.
I will make the changes later as i dont know if i will have the time

**Pull request closed without merging**
