### PR TITLE
Update iters.md

### PR DESCRIPTION
**Pull request by debdutgoswami**
**Update NEW function added**

I have added a new application of the iter() function. I have shown how we can _check if an object in python is iterable or not_.

**Regards,** 
Debdut Goswami

### CODE REVIEW

**Comment by Akuli** [comment]
This looks quite nice. Can you put the new section before the generators section, and use `except TypeError:` instead of plain `except:` ?

**Comment by Akuli** [comment]
There are actually some funny special cases when this doesn't quite work right. Tkinter widgets are one example of this. It's very unlikely that anyone will actually run into this though, and not even worth mentioning IMO.

**Comment by debdutgoswami** [comment]
No I mean sometimes for various user-defined objects, checking of these might be helpful. Anyway, I am gonna make the changes you proposed.

**Comment by debdutgoswami** [comment]
done

**Pull request merged**
